
##################################################################
#######################User Routes################################

POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "admintest",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json


###
POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

##################################################################
#######################Admin Routes#############################

POST http://localhost:8081/admin/grantAdmin
Content-Type: application/json 

{
    "username": "test_admin",
}

##################################################################
#######################Comment Routes#############################

POST http://localhost:8081/comment/postComment
Content-Type: application/json

{
    "username": "testName",
    "text": "This is a comment"
}

// GET COMMENTS
###
GET http://localhost:8081/comment/getAll
Content-Type: application/json

// UPDATE A COMMENT
###
PUT http://localhost:8081/comment/editComment/65e9e43ba2b3dd4f1d4828a2
Content-Type: application/json

{
    "text": "This comment was updated using editComment route"
}

// DELETE A COMMENT
###
DELETE http://localhost:8081/comment/deleteComment/65e9e43ba2b3dd4f1d4828a2
Content-Type: application/json

##################################################################
#######################Profile Routes#############################

#PROFILE Example
#Get All Profiles
###
GET http://localhost:8081/profile/getAll
Content-Type: application/json

#Edit Profile
###
POST http://localhost:8081/profile/editProfile
Content-Type: application/json

{
    "username" : "msaintcyr", 
    "password" : "mac1234"
}

#Delete Profile
###
DELETE http://localhost:8081/profile/deleteProfile
Content-Type: application/json

{
    "message" : "the profile has been deleted"
}

#Create Profile
###
POST http://localhost:8081/profile/createProfile
Content-Type: application/json

{
    "username" : "makenleytest",
    "email" : "msc@gmail.com",
    "password" : "testi12345",
    "bio" : "I am from Medford"
}
